- .github/workflows/test.yaml
- CHANGELOG.md
- LICENSE
- NOTICE
- lib/src/powersync_database.dart
- lib/src/uuid.dart
- pubspec.yaml
- test/crud_test.dart
* License the entire library under Apache 2.0.
* Update uuid dependency.
> v0.4.1, Apache 2.0

- lib/src/open_factory.dart
Enable recursive triggers on opening of db
> chore: enable recursive triggers

- .github/workflows/prepare_release.yml
- .github/workflows/publish.yml
- .github/workflows/scripts/run-pana.sh
- .gitignore
- demos/powersync-supabase-flutter-todolist-demo/pubspec.lock
- packages/powersync/CHANGELOG.md
- packages/powersync/pubspec.yaml
- packages/powersync_attachments_helper/.gitignore
- packages/powersync_attachments_helper/CHANGELOG.md
- packages/powersync_attachments_helper/pubspec.yaml
There are issues with pub spec scoring for attachments package due to pubspec.yml
* Corrected repo URL
* Added flutter SDK dep as this is required for path-provider
* Incremented version
> fix(powersync-attachements-helper): pubspec file

- packages/powersync_attachments_helper/README.md
Fix getting started example and add demo link
> chore: update docs

- demos/powersync-supabase-flutter-todolist-demo/pubspec.lock
- packages/powersync_attachments_helper/CHANGELOG.md
- packages/powersync_attachments_helper/pubspec.yaml
Version bump to update the getting started docs for attachments in pub.dev
> chore(attachments): update getting started example

- demos/supabase-anonymous-auth/README.md
- demos/supabase-anonymous-auth/lib/powersync.dart
- demos/supabase-anonymous-auth/pubspec.lock
- demos/supabase-edge-function-auth/README.md
- demos/supabase-edge-function-auth/lib/powersync.dart
- demos/supabase-edge-function-auth/pubspec.lock
- demos/supabase-todolist/pubspec.lock
- packages/powersync_attachments_helper/CHANGELOG.md
- packages/powersync_attachments_helper/README.md
- packages/powersync_attachments_helper/pubspec.yaml
Fix typos, update package description and fix linting issues
> docs: update readmes

- packages/powersync/lib/src/powersync_database.dart
Adds missing return type to this async library function
> Add return type to PowerSyncDatbase connect

- demos/supabase-todolist/lib/attachments/queue.dart
- packages/powersync_attachments_helper/example/getting_started.dart
- packages/powersync_attachments_helper/lib/src/attachments_queue.dart
- packages/powersync_attachments_helper/lib/src/syncing_service.dart
JPG is currently hardcoded as the file extension
Added argument to allow file extension to be set by user. 
**Note:** At present each file type would need its own queue.
> chore: allow different file extensions

- packages/powersync/README.md
- packages/powersync/example/getting_started.dart
Docs are out of date with implementation
Removed outdated functionality and replaced it with the new way things are done
> docs: update readme and getting started

- demos/supabase-anonymous-auth/pubspec.lock
- demos/supabase-edge-function-auth/lib/widgets/login_page.dart
- demos/supabase-edge-function-auth/lib/widgets/signup_page.dart
- demos/supabase-edge-function-auth/pubspec.lock
- demos/supabase-simple-chat/pubspec.lock
- demos/supabase-todolist/lib/attachments/photo_widget.dart
- demos/supabase-todolist/lib/widgets/login_page.dart
- demos/supabase-todolist/lib/widgets/signup_page.dart
- demos/supabase-todolist/pubspec.lock
- pubspec.lock
Update dependencies and fix lint issues in demos.
These checks were changed in newer Dart/Flutter versions, which is why it wasn't an issue before.
> Fix lint issues in demos

- packages/powersync/lib/src/powersync_database.dart
Picked up in https://github.com/powersync-ja/powersync-js/pull/151
> Fix disconnectAndClear not clearing ps_untyped

- demos/supabase-anonymous-auth/pubspec.lock
- demos/supabase-edge-function-auth/pubspec.lock
- demos/supabase-simple-chat/pubspec.lock
- demos/supabase-todolist/pubspec.lock
- packages/powersync/pubspec.yaml
- Bump powersync version to 1.4.1
> Bump powersync version

- packages/powersync/CHANGELOG.md
This is small PR to update the changelog message for v1.4.0. It adds more information about the changes and why it was upgraded.
> Update existing changelog message for powersync

- CHANGELOG.md
- demos/django-todolist/pubspec.lock
- demos/django-todolist/pubspec.yaml
- demos/supabase-anonymous-auth/pubspec.lock
- demos/supabase-anonymous-auth/pubspec.yaml
- demos/supabase-edge-function-auth/pubspec.lock
- demos/supabase-edge-function-auth/pubspec.yaml
- demos/supabase-simple-chat/pubspec.lock
- demos/supabase-simple-chat/pubspec.yaml
- demos/supabase-todolist/macos/Podfile.lock
- demos/supabase-todolist/pubspec.lock
- demos/supabase-todolist/pubspec.yaml
- packages/powersync/CHANGELOG.md
- packages/powersync/README.md
- packages/powersync/pubspec.yaml
- packages/powersync_attachments_helper/CHANGELOG.md
- packages/powersync_attachments_helper/pubspec.yaml
- Bump `powersync` and `powersync_attachments_helper` versions
- Update Readme
- Update changelog
> Bump versions for web support

- .github/workflows/publish.yml
- Fix `melos publish` to run without user input
> fix: Add yes flag to confirm publishing

- CHANGELOG.md
- demos/django-todolist/pubspec.lock
- demos/django-todolist/pubspec.yaml
- demos/supabase-anonymous-auth/pubspec.lock
- demos/supabase-anonymous-auth/pubspec.yaml
- demos/supabase-edge-function-auth/pubspec.lock
- demos/supabase-edge-function-auth/pubspec.yaml
- demos/supabase-simple-chat/pubspec.lock
- demos/supabase-simple-chat/pubspec.yaml
- demos/supabase-todolist-drift/pubspec.lock
- demos/supabase-todolist-drift/pubspec.yaml
- demos/supabase-todolist/pubspec.lock
- demos/supabase-todolist/pubspec.yaml
- packages/powersync/CHANGELOG.md
- packages/powersync/pubspec.yaml
- packages/powersync_attachments_helper/CHANGELOG.md
- packages/powersync_attachments_helper/pubspec.yaml
- packages/powersync_flutter_libs/CHANGELOG.md
- packages/powersync_flutter_libs/pubspec.yaml
- powersync@1.6.5
- powersync_attachments_helper@0.6.3+2
- powersync_flutter_libs@0.2.0
> chore(release): publish packages

- CHANGELOG.md
- demos/django-todolist/pubspec.lock
- demos/django-todolist/pubspec.yaml
- demos/supabase-anonymous-auth/pubspec.lock
- demos/supabase-anonymous-auth/pubspec.yaml
- demos/supabase-edge-function-auth/pubspec.lock
- demos/supabase-edge-function-auth/pubspec.yaml
- demos/supabase-simple-chat/pubspec.lock
- demos/supabase-simple-chat/pubspec.yaml
- demos/supabase-todolist-drift/pubspec.lock
- demos/supabase-todolist-drift/pubspec.yaml
- demos/supabase-todolist/pubspec.lock
- demos/supabase-todolist/pubspec.yaml
- packages/powersync/CHANGELOG.md
- packages/powersync/pubspec.yaml
- packages/powersync_attachments_helper/CHANGELOG.md
- packages/powersync_attachments_helper/pubspec.yaml
- packages/powersync_flutter_libs/CHANGELOG.md
- packages/powersync_flutter_libs/pubspec.yaml
- Fixes bundling core binaries for `powersync_flutter_libs`
- Fixes running demos in monorepo 
- Bumps versions
> Bump versions

- README.md
- packages/powersync/README.md
> README MySQL updates

- CHANGELOG.md
- demos/benchmarks/pubspec.lock
- demos/django-todolist/pubspec.lock
- demos/supabase-anonymous-auth/pubspec.lock
- demos/supabase-edge-function-auth/pubspec.lock
- demos/supabase-simple-chat/pubspec.lock
- demos/supabase-todolist-drift/pubspec.lock
- demos/supabase-todolist-optional-sync/pubspec.lock
- demos/supabase-todolist/pubspec.lock
- packages/powersync_sqlcipher/CHANGELOG.md
- packages/powersync_sqlcipher/pubspec.yaml
- Update `powersync_flutter_libs` to v0.4.3
> Update powersync_flutter_libs for powersync_sqlcipher

- packages/powersync/pubspec.yaml
This makes the package description of the SDK consistent with the updated values from the JavaScript SDKs: https://github.com/powersync-ja/powersync-js/pull/531
> Update package description

- demos/benchmarks/ios/Podfile.lock
- demos/benchmarks/macos/Podfile.lock
- demos/django-todolist/ios/Podfile.lock
- demos/django-todolist/macos/Podfile.lock
- demos/firebase-nodejs-todolist/ios/Podfile.lock
- demos/supabase-anonymous-auth/ios/Podfile.lock
- demos/supabase-anonymous-auth/macos/Podfile.lock
- demos/supabase-edge-function-auth/ios/Podfile.lock
- demos/supabase-edge-function-auth/macos/Podfile.lock
- demos/supabase-simple-chat/ios/Podfile.lock
- demos/supabase-simple-chat/macos/Podfile.lock
- demos/supabase-todolist-drift/ios/Podfile.lock
- demos/supabase-todolist-drift/macos/Podfile.lock
- demos/supabase-todolist-optional-sync/ios/Podfile.lock
- demos/supabase-todolist-optional-sync/macos/Podfile.lock
- demos/supabase-todolist/ios/Podfile.lock
- demos/supabase-todolist/macos/Podfile.lock
- demos/supabase-trello/ios/Podfile.lock
- demos/supabase-trello/macos/Podfile.lock
- packages/powersync_flutter_libs/android/build.gradle
- packages/powersync_flutter_libs/ios/powersync_flutter_libs.podspec
- packages/powersync_flutter_libs/macos/powersync_flutter_libs.podspec
- packages/sqlite3_wasm_build/build.sh
- scripts/download_core_binary_demos.dart
- scripts/init_powersync_core_binary.dart
Changes: https://github.com/powersync-ja/powersync-sqlite-core/releases/tag/v0.3.13
> Update core extension to 0.3.14
