lib/src/streaming_sync.dart

Instead of just displaying e.g. "401 Authentication Failed", the error details are now parsed from the body.

Improve HTTP error messages

---

.github/workflows/prepare_release.yml
.github/workflows/publish.yml
packages/powersync_attachments_helper/pubspec.yaml

Create automated publishing based on merges to main
* Added prepare_realease action which versions and creates PR with title `chore(release): ...` for publishing
* Added a publish action which publishes to pub.dev whenever a PR with `chore(release): ...` is merged to main
* Fixed github repo reference

chore: automate publishing

---

.github/workflows/prepare_release.yml

Since we don't use conventional commits versioning using melos won't help so all we want is it to create a PR to publish

chore: remove versioning from melos release workflow

---

packages/powersync/lib/src/schema_logic.dart
packages/powersync/test/bucket_storage_test.dart

If a row is modified locally, and the upload batch is completed without the update is not applied on the server (e.g. due to validation or RLS error), the client needs to revert the local update.
This was correctly implemented for INSERT and UPDATE statements, but not for DELETE. The row would remain deleted on the client, instead of re-creating the row after syncing. This fixes the issue by handling deletes in the same way as inserts and updates - storing a marker record in `ps_oplog` until the next sync completes.

Fix reverting failed deletes

---

.github/workflows/demos.yml
.github/workflows/packages.yml

Run the actions on a push to any branch. This runs the actions more often than strictly needed, but reduces the time to wait for actions when opening a PR.

Always runs GitHub Actions

---

demos/supabase-todolist/lib/attachments/camera_helpers.dart
demos/supabase-todolist/lib/attachments/photo_capture_widget.dart
demos/supabase-todolist/lib/attachments/photo_widget.dart
demos/supabase-todolist/lib/main.dart
demos/supabase-todolist/lib/widgets/todo_item_widget.dart

The attachments demo uses the camera, which is only available on Android and iOS.
This changes the camera setup to only run when taking a photo, and display an error if it cannot be initialized (e.g. on desktop).

Handle missing camera in demo

---

demos/supabase-anonymous-auth/lib/widgets/status_app_bar.dart
demos/supabase-edge-function-auth/lib/widgets/status_app_bar.dart
demos/supabase-todolist/lib/models/todo_list.dart
demos/supabase-todolist/lib/widgets/status_app_bar.dart
packages/powersync/lib/src/powersync_database.dart
packages/powersync/lib/src/streaming_sync.dart
packages/powersync/lib/src/sync_status.dart

Changes to SyncStatus:
* Fix `connected` not updating when calling `powersync.disconnect()`.
* Add `connecting`, `downloading` and `uploading` flags.
* Add `downloadError`, `uploadError` and a combined `exception` field.
The demo now uses these to provide more fine-grained connectivity status.
Also includes a minor fix for error parsing that would only return the first character of the error message in some cases.

Improve connection status

---

demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/linux/flutter/generated_plugin_registrant.cc
demos/supabase-simple-chat/linux/flutter/generated_plugins.cmake
demos/supabase-simple-chat/pubspec.lock
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/isolate_completer.dart
packages/powersync/lib/src/powersync_database.dart
packages/powersync/lib/src/powersync_update_notification.dart
packages/powersync/lib/src/schema.dart
packages/powersync/lib/src/uuid.dart
packages/powersync/pubspec.yaml
packages/powersync/test/test_server.dart
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml

powersync package:
- v1.1.0
- Update `sqlite_async` dependency:
- Supports catching errors in transactions and continuing the transaction.
- Add `tx.closed` and `db/tx.getAutoCommit()`
- Update `uuid` dependency:
- Now uses `CryptoRNG` from `uuid` package now that the performance improvements are upstream.
- Requires Dart ^3.2.0 / Flutter ^3.16.0.
powersync_attachments_helper package:
- v0.1.4
- Update dependencies.
- Declare support for Windows, MacOS and Linux platforms.

Update dependencies / powersync v1.1.0

---

packages/powersync/lib/src/open_factory.dart
packages/powersync/test/bucket_storage_test.dart
packages/powersync/test/offline_online_test.dart

1. Fix error occasionally occurring when calling `powersync.connect()` right when opening the database.
> SqliteException(5): while executing, database is locked, database is locked (code 5)
I haven't seen this in an actual app, but it occasionally causes tests to fail such as [this one](https://github.com/powersync-ja/powersync.dart/actions/runs/7397336788/job/20124265094).
2. Fix the "should revert" tests from #39 to do what it says.
3. Fix the "Offline-online Tests" to not depend on order of keys in the JSON output.

Minor Fixes

---

demos/supabase-anonymous-auth/lib/main.dart
demos/supabase-edge-function-auth/lib/main.dart
demos/supabase-todolist/lib/main.dart
demos/supabase-todolist/lib/powersync.dart
packages/powersync/lib/powersync.dart
packages/powersync/lib/src/bucket_storage.dart
packages/powersync/lib/src/connector.dart
packages/powersync/lib/src/exceptions.dart
packages/powersync/lib/src/log.dart
packages/powersync/lib/src/log_internal.dart
packages/powersync/lib/src/powersync_database.dart
packages/powersync/lib/src/streaming_sync.dart
packages/powersync/test/bucket_storage_test.dart
packages/powersync/test/crud_test.dart
packages/powersync/test/offline_online_test.dart
packages/powersync/test/performance_test.dart
packages/powersync/test/powersync_test.dart
packages/powersync/test/stream_test.dart
packages/powersync/test/streaming_sync_test.dart
packages/powersync/test/util.dart
packages/powersync/test/watch_test.dart

This changes the logging behavior to log to console in debug mode by default, instead of logging to the root Logger.
Additionally, error messages are somewhat improved for cases where the error itself is not logged.
To get the old logging behavior back for full control over logging, use `logger: attachedLogger` in the PowerSyncDatabase constructor.
Breaking changes:
1. Exceptions are different in certain conditions.
2. Default logging behavior changed as described above.
3. PowerSyncCredentials does not have a const constructor anymore, and now validates the endpoint URI.
Despite these being breaking changes, I believe it will make debugging significantly easier for new apps, and not impact existing apps significantly.
The example apps still contain the same log handling code, since there …

Improved error logging

---

demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.lock
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/pubspec.yaml

This release improves the default log output and errors to better assist in debugging.
Breaking changes:
- `PowerSyncCredentials` constructor is no longer const, and the `endpoint` URL is validated in the constructor.
- Different error and exception classes are now used by the library, including `CredentialsException`, `SyncResponseException` and `PowerSyncProtocolException`, instead of more generic `AssertionError` and `HttpException`.
Other changes:
- The library now logs to the console in debug builds by default. To get the old behavior, use `logger: attachedLogger` in the `PowerSyncDatabase` constructor.
- Log messages have been improved to better explain the sync process and errors.
See #53 for details.

powersync v1.2.0

---

packages/powersync/CHANGELOG.md
packages/powersync/lib/src/schema_logic.dart
packages/powersync/pubspec.yaml
packages/powersync/test/schema_test.dart

Issue 1: Indexes were incorrectly dropped when updating the schema for unchanged tables (i.e. on the second run).
Issue 2: Using explicit `viewName` overrides (added in #20) could cause `view "..." already exists` errors.

Fix schema changes

---

packages/powersync/README.md
packages/powersync/lib/src/connector.dart
packages/powersync/test/credentials_test.dart

This adds quite a lot of detail to the README, I think it's basically everything that I would have needed to get Hello World up and running.
I'm not sure how you feel about about having a longer readme versus moving more detail to examples/. Personally I find it quite useful to have the main gist of things in a Readme that I can read from top to bottom.
I also fixed a small bug in `getExpiryDate` that I ran into. JWTs don't use padding but it seems that [dart:convert requires padding even for base64Url encoding](https://api.flutter.dev/flutter/dart-convert/base64Url-constant.html).

More detailed README and small bugfix

---

demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-simple-chat/pubspec.lock
demos/supabase-todolist/pubspec.lock
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/connector.dart
packages/powersync/lib/src/open_factory.dart
packages/powersync/lib/src/powersync_database.dart
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/lib/src/syncing_service.dart

Remove references to DevConnector

chore: remove devconnector references

---

demos/supabase-simple-chat/README.md
demos/supabase-simple-chat/ios/Podfile
demos/supabase-simple-chat/ios/Podfile.lock
demos/supabase-todolist/README.md
demos/supabase-todolist/ios/Podfile
demos/supabase-todolist/ios/Podfile.lock

Update `podfile.lock` to avoid error

chore: update podfile.lock

---

demos/supabase-todolist/lib/attachments/queue.dart
demos/supabase-todolist/pubspec.lock
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/README.md
packages/powersync_attachments_helper/example/getting_started.dart
packages/powersync_attachments_helper/lib/src/attachments_queue.dart
packages/powersync_attachments_helper/lib/src/attachments_service.dart
packages/powersync_attachments_helper/lib/src/syncing_service.dart
packages/powersync_attachments_helper/pubspec.yaml

Improve attachment queue so that multiple uploads, downloads and deletes don't run simultaneously. This is related to this support query in discord https://discord.com/channels/1138230179878154300/1220388800455250082
* Replaced `watchDownloads`, `watchUploads` and `watchDeletes` into a single watcher `watchAttachments` so that duplicate upload, download or delete function calls do not occur when table is updated.
* Replaced `runDownloads`, `runUploads` and `runDeletes` into a single function `runSync` so that duplicate upload, download or delete function calls do not occur when table is updated.
* Updated dependencies
* Updated docs
* Delete the demo app from the device you are using. Make sure you have set a bucket in config.
* Install the demo app and log in
* You should see a watcher …

fix: attachment queue duplicating requests

---

demos/supabase-todolist/pubspec.lock
packages/powersync/lib/src/powersync_database.dart

Add crud throttle option on connect
Added optional throttle argument to `connect`

chore: add crud throttle option

---

packages/powersync/lib/src/powersync_database.dart
packages/powersync/pubspec.yaml
packages/powersync/test/streaming_sync_test.dart
packages/powersync/test/test_server.dart

Usually, when calling `connect()` a second time, it closes the first connection first. However, when calling it twice in quick succession, a race condition caused both connections were opened. This typically then ends up with "Checksum mismatch" failures.
This fixes the issue by wrapping connect() in a Mutex.
This also bumps sqlite_async to v0.6.1. This includes improvements in handling of SQLITE_BUSY errors, which affected these tests.

Fix "Checksum mismatch" when calling connect() multiple times

---

demos/supabase-todolist/pubspec.lock
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/lib/src/attachments_queue.dart
packages/powersync_attachments_helper/lib/src/attachments_service.dart
packages/powersync_attachments_helper/lib/src/syncing_service.dart
packages/powersync_attachments_helper/pubspec.yaml

Minor improvements based on feedack
* Added a scheduled sync task that runs a sync and deletes archived data
* Fixed loop to use continue instead of return
* Removed unnecessary `executeBatch` delete

chore(attachments): minor improvements and fix loop

---

packages/powersync_attachments_helper/lib/src/syncing_service.dart

The `isProcessing` property needs to be reset if an error is thrown during a sync so that subsequent sync attempts can be made. If it's not reset, then it's always `true` and will never sync again until the app is closed and re-opened.

Reset isProcessing when exception is thrown during sync process.

---

demos/supabase-todolist/lib/attachments/photo_capture_widget.dart
demos/supabase-todolist/lib/attachments/queue.dart
demos/supabase-todolist/lib/widgets/todo_item_widget.dart
demos/supabase-todolist/pubspec.lock
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/README.md
packages/powersync_attachments_helper/example/getting_started.dart
packages/powersync_attachments_helper/lib/src/attachments_queue.dart
packages/powersync_attachments_helper/pubspec.yaml

* Allow subdirectories in storage to also be used in attachments queue
* Rename methods to make them more general
* Allow subdirectories to be set on queue initializing which will create a subdirectory locally to match what is on remote storage
* Renamed `savePhoto` and `deletePhoto` methods to `saveFile` and `deleteFile` - this introduces a BREAKING CHANGE
Using todolist demo:
1. When initializing the queue in `queue.dart` add a subdirectory e.g. ['cover-images']
```
PhotoAttachmentQueue(db, remoteStorage)
: super(
db: db,
remoteStorage: remoteStorage,
onDownloadError: onDownloadError,
subdirectories: ['cover-images']);
```
2. Update `_takePhoto` method in `photo_capture_widget.dart` to this (bold is what has been changed, the ID now captures the subdirectory):
```
Future<void> …
```

feat(attachments)!: cater for subdirectories in storage

---

CHANGELOG.md
demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.lock
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/database/web/web_powersync_database.dart
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml

A recent issue https://github.com/powersync-ja/powersync.dart/issues/11#issuecomment-2133967076 showed that under certain conditions the sync stream network request would fail in web.
We currently use the [fetch_client](https://pub.dev/packages/fetch_client) package to  bind to the JS `fetch` method. This supports streaming for request body and request responses. The streaming of request bodies requires `Chromium 105+ based browsers and requires server to use HTTP/2 or HTTP/3`. We only require streaming for request responses. This allows us to remove the `streamRequests: true` param and maintain better compatibility.
This PR also updates `sqlite_async.dart` to the latest alpha version.
This was tested in the Supabase todolist app. The sync stream connection was verified by having data …

[Fix] Sync stream connection

---

demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.lock
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/pubspec.yaml
packages/powersync_flutter_libs/CHANGELOG.md
packages/powersync_flutter_libs/android/build.gradle
packages/powersync_flutter_libs/pubspec.yaml

The work was verified by running it on an android emulator (API 21), ensuring the extension loads and `db.get('select powersync_rs_version()')` returns version 0.1.7.
- Upgrade powersync-sqlite-core to version 0.1.7 for Android
- Upgrade `powersync_flutter_libs` to version 0.1.0
- Bump `powersync` to version 1.4.1

Upgrade powersync-sqlite-core to version 0.1.7 for Android

---

demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/abort_controller.dart
packages/powersync/pubspec.yaml

There was an error of `Flutter Bad state: Future already completed` when calling `disconnectAndClear()` in the demo apps. This was fixed by ensuring the abort future was not completed twice. 
- Ensure abort future is not completed before calling `.complete()`

Check if abort future is completed before completing it

---

demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.lock
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist/ios/Podfile.lock
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/abort_controller.dart
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/pubspec.yaml

There was an error of Flutter Bad state: Future already completed when calling disconnectAndClear() in the demo apps. This was fixed by ensuring the abort future was not completed twice.
- Ensure abort future is not completed before calling .complete() for web

Prevent completing futures twice for web

---

demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.lock
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/bucket_storage.dart
packages/powersync/lib/src/database_utils.dart
packages/powersync/lib/src/open_factory.dart
packages/powersync/lib/src/powersync_database.dart
packages/powersync/lib/src/schema_logic.dart
packages/powersync/pubspec.yaml
packages/powersync/test/bucket_storage_test.dart
packages/powersync/test/util.dart
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml

This upgrades `sqlite_async` to version 0.7.0 which requires the minimum dart SDK version 3.4.0 and fixes the `Invalid argument(s): argument value for 'return_value' is null` error when closing the database connection.
This also updates all the Database types to a `CommonDatabase` type.

Upgrade sqlite_async

---

packages/powersync_flutter_libs/example/README.md
packages/powersync_flutter_libs/lib/powersync_flutter_libs.dart

Currently some of the CI checks for Dart package scores are failing. See [reference](https://github.com/powersync-ja/powersync.dart/actions/runs/9717540494/job/26823430677?pr=108).
This PR adds an example and some documentation comments to `powersync_flutter_libs` to bring the score value up to the required score threshold. 
This example is based off [this](https://github.com/simolus3/sqlite3.dart/blob/main/sqlite3_flutter_libs/example/README.md).

[Chore] Fix Pana Score Checks

---

packages/powersync/CHANGELOG.md
packages/powersync/lib/src/powersync_database.dart
packages/powersync/pubspec.yaml

- Refactor `waitForFirstSync()` to iterate through the stream and remove the use of a `Future`.

Fix Future already completed when calling waitForFirstSync

---

CHANGELOG.md
demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.lock
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/database/native/native_powersync_database.dart
packages/powersync/lib/src/open_factory/abstract_powersync_open_factory.dart
packages/powersync/lib/src/open_factory/native/native_open_factory.dart
packages/powersync/pubspec.yaml
packages/powersync/test/utils/native_test_utils.dart
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml
pubspec.lock
pubspec.yaml

This updates the `sqlite_async` package to `0.8.0` which now contains web support.
Testing: Verified that the Supabase Todolist app works as expected.

[Chore] Update Sqlite Async Web

---

CHANGELOG.md
demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.lock
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/database/web/web_powersync_database.dart
packages/powersync/lib/src/streaming_sync.dart
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml

This uses the Navigator locks in the `Mutex` class from here https://github.com/powersync-ja/sqlite_async.dart/pull/54 to limit the number of active sync implementations when multiple tabs are used.
This is only a stop-gap to prevent multiple tabs with multiple `StreamingSyncImplementation`s from applying sync bucket changes at the same time (this can leave the local SQLite DB in an inconsistent or broken state).
This method enhances the safety of using multiple tabs, but is far from complete multiple tab support. 
This should address the issue of "Flutter web + PowerSync still has the issue where multiple open tabs will cause sqlite to get messed up"  from https://github.com/powersync-ja/powersync.dart/issues/11
Note that the app works when switching between tabs. The sync status is …

[Feature] Implement web sync locks

---

demos/django-todolist/README.md
demos/django-todolist/lib/app_config_template.dart
demos/django-todolist/macos/Podfile.lock

This updates the Django demo with local development instructions.

[Chore] Update Django Demo Readme

---

demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.lock
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/powersync_database.dart
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml

Addresses the enhancement in #116 with `watch` queries not recognizing powersync table names.
- Prepend powersync identifiers to tables specified in a the `triggerOnTables` parameter in a watch query.
- Upgrade dependency `sqlite_async` to 0.8.1

Fix watch query table names

---

CHANGELOG.md
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist/macos/Podfile.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/powersync_database.dart
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/pubspec.yaml

Currently the `hasSynced` member of `SyncStatus` does not work if the device is offline.
The value is initially set to true after querying `ps_buckets` but if a sync request fails it's value will be cleared.
When starting offline
Note that `lists` are present on the device

[Fix] Offline has synced

---

CHANGELOG.md
demos/django-todolist/pubspec.lock
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.lock
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml

This release adds a bunch of improvements and bug fixes for the powersync alpha release. These changes were pulled in from the upstream `master` branch.
- Update powersync dependency to version 1.6.0-alpha.1
- Update powersync_attachments_helper dependency to version 0.6.0-alpha.1
- Update changelogs

Update powersync dependency to version 1.3.0-alpha.10

---

packages/powersync/test/crud_test.dart

This is to fix the merge conflicts from merging alpha release into master in PR #61 
- Merge changes from master into alpha release

Merge master to alpha release

---

.github/workflows/release.yml
CHANGELOG.md
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist/pubspec.yaml
melos.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/database/powersync_db_mixin.dart
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml

The `waitForFirstSync` method was removed during the merge from alpha-release to master. This adds it back.
- Reintroduce waitForFirstSync
- Improve versioning and releases using `melos`

Reintroduce waitForFirstSync

---

.github/workflows/release.yml

The `gh` cli action requires the github token to create a release.

Update release workflow to include environment variables

---

CHANGELOG.md
demos/django-todolist/pubspec.lock
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.lock
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml

There is a build error in FlutterFlow as some of packages used by default rely on `js: 0.6.7`. We only use the JS dependency for web tests and the package downgrade does not break those tests.
```
Error Getting Packages
Check the following custom dependencies: powersync: ^1.6.2.
Because sign _in_with_apple_web <2.0.0-dev.1 depends on js ^0.6.3 
and powersync>=1.6.0-alpha.1 depends on js ^0.7.0, 
sign in with_apple _web <2.0.0-dev.1 is incompatible with powersync >=1.6.0-alpha.1.
```
- Downgrade JS dependency to version 0.6.7

Downgrade JS dependency to version >=0.6.7 <0.8.0

---

CHANGELOG.md
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/database/powersync_db_mixin.dart
packages/powersync/lib/src/streaming_sync.dart
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml

The `hasSycned` status would be retained after calls to `disconnectAndClear` have been made. 
Steps to reproduce the issue:
- Log in
- Wait for first sync > works fine
- Log out
- Log in
- Wait for first sync > no longer works
The previous `hasSynced: true` would cause the check to immediately pass before syncing had completed on the second round. 
This PR clears the `hasSynced` status when disconnecting and clearing. The PowerSync client typically checks the setting in the `initialize` method which won't be called again, but the status will be updated on the next full sync when `lastSyncedAt` has been set.
This was tested on MacOS by syncing locally then logging out. The local PowerSync service was then stopped to delay the syncing process. The next login should show the loading message …

[Fix]  Reset hasSynced

---

demos/supabase-todolist-drift/README.md

To make it more Drift specific.

Update Drift Demo Readme 

---

.github/workflows/publish.yml

Version solving fails if the `pubspec_overrides.yaml` is not generated before running `melos publish (dart pub publish --dry-run)`. It tends to look for a new version online before it has been published. This change ensures that the override is present before trying to validate the pubspec.
- Add step to install dependencies and generate a `pubspec_overrides.yaml` so that version solving does not fail when validating the pubspec with `melos publish`.
- Only run publish workflow once per tag push

fix: Run melos bootstrap before publishing

---

packages/powersync/lib/src/database/native/native_powersync_database.dart
packages/powersync/lib/src/database/web/web_powersync_database.dart
packages/powersync/lib/src/schema.dart
packages/powersync/test/schema_test.dart

Users currently only see an error for maxmium number of columns at runtime. This adds a check so that they would see it on Table creation.
* Added checks to Table and added some Table specific tests

chore(powersync): add max column check

---

CHANGELOG.md
RELEASING.md
packages/powersync/CHANGELOG.md

Rectify issue with release that added incorrect changes to the changelog

docs: fix changelog

---

.github/workflows/demos.yml
melos.yaml

Having a `melos run` command on multiple lines works on macOS and Linux but fails to run additional new lines on windows
- Make all prepare commands run in a single line with & separators.

Make melos prepare command a single line

---

CHANGELOG.md
demos/django-todolist/pubspec.lock
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.lock
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.lock
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/user_agent/user_agent_native.dart
packages/powersync/lib/src/user_agent/user_agent_web.dart
packages/powersync/lib/src/version.dart
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml

Release v1.8.0

---

CHANGELOG.md
demos/django-todolist/pubspec.lock
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.lock
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.lock
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/version.dart
packages/powersync/pubspec.yaml
packages/powersync_flutter_libs/CHANGELOG.md
packages/powersync_flutter_libs/pubspec.yaml

https://github.com/powersync-ja/powersync.dart/pull/155 missed the version bump to powersync_flutter_libs, causing:
>  SqliteException(1): Unsupported powersync extension version. Need ˆ0.2.0, got 0.1.6/14f7c2b0
See #156.

powersync 1.8.1 / powersync_flutter_libs 0.3.0

---

CHANGELOG.md
demos/django-todolist/pubspec.lock
demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-simple-chat/pubspec.lock
demos/supabase-todolist-drift/pubspec.lock
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.lock
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml

- Bump powersync_attachments_helper to v0.6.6

Upgrade and publish `powersync_attachments_helper` package

---

packages/powersync/lib/src/database/powersync_db_mixin.dart
packages/powersync/lib/src/open_factory/native/native_open_factory.dart

The SDK will now print the exception message for unsupported platforms when loading the core extension. The error message will state if the platform is unsupported. Addresses the issue reported in #166.
```
I/flutter ( 6406): [PowerSync] SEVERE: 2024-09-19 16:27:01.970790: Unsupported processor architecture. 
X86 Android emulators are not supported. 
Please use an x86_64 emulator instead. All physical Android devices are supported including 32bit ARM.
```
- Print exception message when loading extension
- Remove unused imports

Handle `PowersyncNotReadyException` printing the message for the user

---

demos/supabase-todolist-optional-sync/lib/models/schema.dart

Original issue reported in dart optional sync demo https://github.com/powersync-ja/powersync.dart/discussions/174.
This ensures that we correctly copy over the todos with the authed user ID instead of the default local ID.
Instead of copying the local data over to the sync table verbatim (and getting the owner ID from the local table), we use the newly logged in user's ID.

Fixed updating schema when moving todos to synced table

---

demos/django-todolist/lib/api_client.dart
demos/django-todolist/lib/main.dart
demos/django-todolist/lib/powersync.dart
demos/django-todolist/lib/widgets/login_page.dart

Currently Shared Preferences are not removed on logout as described in https://github.com/powersync-ja/powersync.dart/issues/167
* Updated deprecated `SharedPreferences` to use `SharedPreferencesAsync`. 
* Removed duplicate logger
Confirmed preferences are set on log in and are unset on log out.

chore(demos): remove shared preferences on logout

---

CHANGELOG.md
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.yaml
demos/supabase-todolist/ios/Podfile.lock
demos/supabase-todolist/macos/Podfile.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/database/native/native_powersync_database.dart
packages/powersync/lib/src/database/powersync_database.dart
packages/powersync/lib/src/version.dart
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml

Originally created by David Martos in #171. Prior to this fix the maxReaders was always set to the default of 5 read connections and would not be changed according to the parameter passed in. This fix ensures that the maxReaders parameter is propagated down to the SQLite factory to create multiple read connections.
- Pass maxReaders parameter to PowerSync.withFactory

Pass maxReaders parameter to PowerSync.withFactory

---

CHANGELOG.md
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.yaml
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/bucket_storage.dart
packages/powersync/lib/src/streaming_sync.dart
packages/powersync/lib/src/version.dart
packages/powersync/pubspec.yaml
packages/powersync/test/upload_test.dart
packages/powersync/test/utils/abstract_test_utils.dart
packages/powersync/test/utils/web_test_utils.dart
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml

This is a backport of a feature added to the powersync js SDK. It ensures that there is a warning displayed when the same `CrudEntry` is processed by the upload loop. See this [PR](https://github.com/powersync-ja/powersync-js/pull/254) in the JS SDK for a more detailed explanation.
- Display warning if crud transactions are in queue to be uploaded

[Feature] Add warning if crud transactions are not completed

---

demos/django-todolist/ios/Podfile.lock
demos/django-todolist/pubspec.lock
demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-simple-chat/pubspec.lock
demos/supabase-todolist-drift/ios/Podfile.lock
demos/supabase-todolist-drift/pubspec.lock
demos/supabase-todolist-optional-sync/ios/Podfile.lock
demos/supabase-todolist-optional-sync/pubspec.lock
demos/supabase-todolist/ios/Podfile.lock
demos/supabase-todolist/pubspec.lock
melos.yaml
packages/powersync/bin/setup_web.dart
packages/powersync/lib/src/database/powersync_db_mixin.dart
packages/powersync_flutter_libs/android/build.gradle
packages/powersync_flutter_libs/ios/powersync_flutter_libs.podspec
packages/powersync_flutter_libs/macos/powersync_flutter_libs.podspec
scripts/download_core_binary_demos.dart
scripts/init_powersync_core_binary.dart

Release notes: https://github.com/powersync-ja/powersync-sqlite-core/releases/tag/v0.3.0
> This release removes major performance bottlenecks during incremental sync. Previously, incremental sync would have overhead proportional to the number of synced rows, which typically caused noticeable latency when syncing around 10-100k+ rows. Now, the overhead is only proportional to the number of buckets synced.
> 
> The performance improvements required a restructure in the data storage format. Data is migrated automatically, and an app can downgrade back to v0.2.0 or v0.2.1 of powersync-sqlite-core.
> 
> Changes:
>  * Persist checksums to improve incremental sync performance.
>  * Restructure persistence of REMOVE operations to further improve incremental sync performance.
>  * Create internal …

powersync-sqlite-core 0.3.0

---

demos/django-todolist/pubspec.lock
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.lock
demos/supabase-todolist-drift/lib/database.g.dart
demos/supabase-todolist-drift/pubspec.lock
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.lock
demos/supabase-todolist-optional-sync/pubspec.yaml
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/pubspec.yaml

Updates sqlite_async version in the package and in the demos, and it updates the drift demo with an up to date version.
Depends on https://github.com/powersync-ja/sqlite_async.dart/pull/65

bump sqlite_async version to 0.9.0

---

packages/powersync/lib/src/schema.dart
packages/powersync/test/schema_test.dart

Currently calling `validate()` on a schema does not check for duplicate table names. This checks that there are no duplicate table names and throws an assertion error if there are duplicates.
- Check for duplicate table names in schema validation

Fix: Validate duplicate table names

---

CHANGELOG.md
demos/django-todolist/pubspec.lock
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.lock
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.lock
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.lock
demos/supabase-todolist-optional-sync/pubspec.yaml
demos/supabase-todolist/ios/Podfile.lock
demos/supabase-todolist/macos/Podfile.lock
demos/supabase-todolist/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
demos/supabase-todolist/pubspec.lock
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/version.dart
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml
packages/powersync_flutter_libs/CHANGELOG.md
packages/powersync_flutter_libs/android/build.gradle
packages/powersync_flutter_libs/ios/powersync_flutter_libs.podspec
packages/powersync_flutter_libs/macos/powersync_flutter_libs.podspec
packages/powersync_flutter_libs/pubspec.yaml
scripts/download_core_binary_demos.dart
scripts/init_powersync_core_binary.dart

This PR updates powersync-sqlite-core to version 0.3.4. It addresses the issues raised in #197. The underlying xcframework used by the cocoapod (`powersync-sqlite-core`) did not have the correct directory structure and symlinks which caused an error when deploying a macOS app to TestFlight or the AppStore. This was fixed in this [PR](https://github.com/powersync-ja/powersync-sqlite-core/pull/41). 
- Upgrade powersync-sqlite-core to v0.3.4

Fix: Malformed Framework macOS

---

.github/workflows/demos.yml
.github/workflows/packages.yml
demos/django-todolist/pubspec.lock
demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-simple-chat/pubspec.lock
demos/supabase-todolist-drift/pubspec.lock
demos/supabase-todolist-optional-sync/pubspec.lock
demos/supabase-todolist/pubspec.lock
packages/powersync/lib/src/database/native/native_powersync_database.dart
packages/powersync/lib/src/database/web/web_powersync_database.dart
packages/powersync/lib/src/streaming_sync.dart
packages/powersync/lib/src/web/powersync_db.worker.dart
packages/powersync/pubspec.yaml
packages/powersync/test/crud_test.dart
packages/powersync_attachments_helper/pubspec.yaml

The is a combination of multiple related issues:
1. To detect whether we should trigger a crud upload iteration, the entire database was watched, instead of only the `ps_crud` table.
2. Update notifications were not throttled at all on web, and not correctly handled during transactions (see https://github.com/powersync-ja/sqlite_async.dart/pull/68 for the issue and fix).
3. The connection status was changed to `uploading: true` whenever we get an update notification, rather than only when there is something to upload.
The result was that on Flutter web, after an initial sync of 10k+ rows, there would be a couple of seconds of the sync indicator flickering between "uploading" and "connected". This also added performance overhead.
TODO:

Fix upload queue monitoring issues

---

CHANGELOG.md
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.yaml
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/streaming_sync.dart
packages/powersync/lib/src/version.dart
packages/powersync/pubspec.yaml
packages/powersync/test/connected_test.dart
packages/powersync/test/server/sync_server/mock_sync_server.dart
packages/powersync/test/streaming_sync_test.dart
packages/powersync/test/upload_test.dart
packages/powersync/test/utils/abstract_test_utils.dart
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml
packages/powersync_flutter_libs/CHANGELOG.md
packages/powersync_flutter_libs/pubspec.yaml

This fixes an issue where CRUD uploads are not triggered when the SDK reconnects to the PowerSync service after being offline.
Previously uploads were only triggered when an initial call to `.connect` has been made or when changes to the `ps_crud` table have occurred. If an application called `.connect` successfully, then went offline and made CRUD operations - the SDK would not trigger a CRUD upload once it had re-established a connection.
This now triggers a CRUD upload whenever the SDK establishes a connection or a change has been made to `ps_crud`.
This was tested locally and unit tests have been added using a mock PowerSync service.

[Fix] CRUD Upload on Reconnect

---

packages/powersync/README.md

Update `powersync` package readme to reflect the beta release of Web support (https://github.com/powersync-ja/powersync.dart/pull/200)

Update readme to reflect flutter web beta

---

CHANGELOG.md
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.yaml
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/version.dart
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml

This bumps packages in order to update pub.dev readmes for the Flutter Web Beta release.

chore: version packages

---

packages/powersync/README.md

Most content will be moved to [docs](https://docs.powersync.com/client-sdk-references/flutter/flutter-web-support), so only keep the essential getting started instructions in the Readme.
Depends on https://github.com/powersync-ja/mintlify-docs/pull/17/files

Simplify Flutter Web Readme

---

.github/workflows/release.yml
RELEASING.md

The PowerSync SDK requires assets for Webworkers which are downloaded from Github releases. The SDK release process currently creates a draft Github Release which needs to be reviewed an published manually. This step is often forgotten.
This PR updates the release process to publish the release as it is created. The Github release's body is taken from the corresponding version entry in the PowerSync package's CHANGELOG.md file. This release can still be edited after publish.

chore: Improve Release Automation

---

.github/workflows/demos.yml
.github/workflows/packages.yml
CHANGELOG.md
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.yaml
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/bucket_storage.dart
packages/powersync/lib/src/version.dart
packages/powersync/lib/src/web/sync_worker.dart
packages/powersync/lib/src/web/web_bucket_storage.dart
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml
scripts/compile_webworker.dart

An [update](https://github.com/powersync-ja/sqlite_async.dart/pull/77) in sqlite_async will automatically flush each write. This gives some durability guarantees, but significantly slows down initial sync of 100k rows.
This change configures bucket storage to selectively disable flushing in cases where durability is not important. This only has an effect for Flutter Web, and only when IndexedDB storage is used.
Despite this change, OPFS storage is still much better. This just makes IndexedDB storage a little less bad.

IndexedDB flushing

---

CHANGELOG.md
demos/benchmarks/pubspec.yaml
demos/django-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.yaml
demos/supabase-todolist/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/lib/src/version.dart
packages/powersync/pubspec.yaml
packages/powersync/test/bucket_storage_test.dart
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml
packages/powersync_flutter_libs/CHANGELOG.md
packages/powersync_flutter_libs/android/build.gradle
packages/powersync_flutter_libs/ios/powersync_flutter_libs.podspec
packages/powersync_flutter_libs/macos/powersync_flutter_libs.podspec
packages/powersync_flutter_libs/pubspec.yaml
scripts/download_core_binary_demos.dart
scripts/init_powersync_core_binary.dart

Test case and fix for https://github.com/powersync-ja/powersync-sqlite-core/pull/45

powersync-sqlite-core 0.3.6

---

packages/powersync_core/lib/src/open_factory/web/web_open_factory.dart
packages/powersync_core/lib/src/web/powersync_db.worker.dart
packages/powersync_core/lib/src/web/worker_utils.dart
packages/powersync_core/pubspec.yaml

When we're running in a context where workers haven't been set up (like e.g. the Test Run environment from FlutterFlow), fall back to hosting the SQLite database in the main JavaScript context. This also requires setting up the powersync extension, which is normally initialized by the worker.
The new `sqlite_async` / `sqlite3_web` package versions will use our database controller when workers are unavailable.

Web: Enable PowerSync extensions even without worker

---

packages/powersync_core/lib/src/web/sync_controller.dart
packages/powersync_core/lib/src/web/sync_worker_protocol.dart

When we use a worker for the streaming sync implementation, we currently have an independent `autoLogger` for that. This makes it impossible for users to customize or disable the logs emitted by the worker.
By re-using the logger from the `PowerSyncDatabase` instead, users can customize the log levels. Closes https://github.com/powersync-ja/powersync.dart/issues/225.
Unfortunately this is hard to test without setting up integration tests as it requires the worker. The fix can be verified manually by applying the snippet suggested in #225 in an example project:
```diff
diff --git a/demos/supabase-todolist/lib/powersync.dart b/demos/supabase-todolist/lib/powersync.dart
index 166de1b..4e1cbf1 100644
--- a/demos/supabase-todolist/lib/powersync.dart
+++ …
```

Use database logger for sync protocol

---

packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/analysis_options.yaml
packages/powersync_attachments_helper/pubspec.yaml
packages/powersync_core/pubspec.yaml
packages/powersync_core/test/connected_test.dart
packages/powersync_core/test/performance_native_test.dart
packages/powersync_core/test/powersync_native_test.dart
packages/powersync_core/test/server/worker_server.dart
packages/powersync_core/test/stream_test.dart
packages/powersync_core/test/streaming_sync_test.dart
packages/powersync_core/test/upload_test.dart
packages/powersync_core/test/utils/web_test_utils.dart
packages/powersync_core/test/watch_test.dart
packages/powersync_flutter_libs/lib/powersync_flutter_libs.dart
packages/powersync_flutter_libs/pubspec.yaml
packages/powersync_sqlcipher/pubspec.yaml

In `package:powersync_core`, migrate away from `package:dcli` and `package:js` so that we're compatible with the latest version of all dependencies.
Apart from that, this updates `package:lints` and fixes the new analysis warnings.

Update lints and dependencies in released packages

---

CHANGELOG.md
demos/benchmarks/pubspec.yaml
demos/django-todolist/pubspec.yaml
demos/firebase-nodejs-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.yaml
demos/supabase-todolist/pubspec.yaml
demos/supabase-trello/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml
packages/powersync_core/CHANGELOG.md
packages/powersync_core/lib/src/version.dart
packages/powersync_core/pubspec.yaml
packages/powersync_flutter_libs/CHANGELOG.md
packages/powersync_flutter_libs/pubspec.yaml
packages/powersync_sqlcipher/CHANGELOG.md
packages/powersync_sqlcipher/pubspec.yaml

There's nothing too exciting since the last release, but I want to test the new publishing workflows with the custom WASM build before the next minor release for `package:powersync` (since `setup_web.dart` will start looking in this repository for WASM files at that point).
So, this release includes the migrations to strict inference everywhere and updates the core extension to 0.3.10.

Release packages

---

.github/workflows/release.yml

Releasing the npm package for FlutterFlow [failed due to missing auth](https://github.com/powersync-ja/powersync.dart/actions/runs/13386172841). That release is not critical, but adding this step should fix subsequent releases.

Add missing auth configuration for npm publishing

---

packages/powersync_core/lib/powersync_core.dart
packages/powersync_core/lib/src/database/core_version.dart
packages/powersync_core/lib/src/database/powersync_db_mixin.dart
packages/powersync_core/lib/src/powersync_database.dart
packages/powersync_core/test/database/core_version_test.dart
packages/sqlite3_wasm_build/build.sh
scripts/init_powersync_core_binary.dart

When opening databases, we check whether the version of the core extension we've loaded is compatible with our Dart SDK. This check was not updated for the update to bucket priorities, allowing SDK versions `<0.3.11` to be used. This breaks immediately afterwards when selecting from `ps_sync_state`.
This updates the version check to the new minimum version and refactors the check to make minimum and maximum versions easier to update the future.
When the version check fails on the web (the most likely cause since we expect `powersync` and `powersync_flutter_libs` to be updated as one, but require users to update our WebAssembly files manually), this also improves the error message to point to the docs explaining how to update these assets.
Resolves …

Improve compatibility check for core extension

---

CHANGELOG.md
demos/benchmarks/pubspec.yaml
demos/django-todolist/pubspec.yaml
demos/firebase-nodejs-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.yaml
demos/supabase-todolist/pubspec.yaml
demos/supabase-trello/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml
packages/powersync_core/CHANGELOG.md
packages/powersync_core/lib/src/database/web/web_powersync_database.dart
packages/powersync_core/lib/src/version.dart
packages/powersync_core/lib/src/web/sync_controller.dart
packages/powersync_core/pubspec.yaml
packages/powersync_core/test/in_memory_sync_test.dart
packages/powersync_core/test/server/sync_server/in_memory_sync_server.dart
packages/powersync_sqlcipher/CHANGELOG.md
packages/powersync_sqlcipher/pubspec.yaml

This fixes the issue [reported here](https://discord.com/channels/1138230179878154300/1344044450191773746). When the sync service calls `invalidCredentialsCallback`, the app should fetch new credentials which are then cached by the connector. For this, we need to call `prefetchCredentials`. `fetchCredentials`, the method we used to call, obtains credentials without saving them.
We were already calling `prefetchCredentials` on native platforms, but the web implementation was broken and never refreshed the token. This caused us to keep using the expired token, entering an infinite loop of 401 errors.

Fix broken token invalidation on web

---

packages/powersync_core/lib/src/streaming_sync.dart
packages/powersync_core/test/in_memory_sync_test.dart
packages/powersync_core/test/server/sync_server/in_memory_sync_server.dart

This is the Dart port of https://github.com/powersync-ja/powersync-js/pull/558, see that PR for details.

Fix race condition for checkpoints during uploads

---

packages/powersync_core/lib/src/abort_controller.dart
packages/powersync_core/lib/src/database/active_instances.dart
packages/powersync_core/lib/src/database/native/native_powersync_database.dart
packages/powersync_core/lib/src/database/powersync_database_impl_stub.dart
packages/powersync_core/lib/src/database/powersync_db_mixin.dart
packages/powersync_core/lib/src/database/web/web_powersync_database.dart
packages/powersync_core/lib/src/isolate_completer.dart
packages/powersync_core/lib/src/streaming_sync.dart
packages/powersync_core/test/schema_test.dart
packages/powersync_core/test/streaming_sync_test.dart

The existing implementation around `connect()` and `disconnect()` has a bit of an odd control flow. I couldn't find any likely race conditions, but this still cleans up the implementation a bit to be easier to reason about. In particular, some of the things this addresses:
1. While we acquire a mutex for `connect()`, we were not doing this for `disconnect()`.  So if we call `connect()` and then immediately call `disconnect()`, it's possible that `disconnect()` does nothing because the `AbortController` has not yet been set.
2. `reconnect()` doesn't actually check if we still need to connect, so a `disconnect()` call followed by an error on the isolate could cause another `connect()` that is not stopped.
3. We set an `onExit` port when spawning the isolate, but there's a separate …

Refactor connection locks

---

CHANGELOG.md
demos/benchmarks/pubspec.yaml
demos/django-todolist/pubspec.yaml
demos/firebase-nodejs-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.yaml
demos/supabase-todolist/pubspec.yaml
demos/supabase-trello/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml
packages/powersync_core/CHANGELOG.md
packages/powersync_core/lib/src/version.dart
packages/powersync_core/pubspec.yaml
packages/powersync_sqlcipher/CHANGELOG.md
packages/powersync_sqlcipher/pubspec.yaml

This prepares to publish changes since [the last release](https://github.com/powersync-ja/powersync.dart/compare/powersync-v1.12.2...main). Notable changes include the `connect` / `disconnect` refactoring, fixing token invalidation on the web and warnings/mutexes for sync that are now shared across databases on the same isolate.

Publish packages

---

CHANGELOG.md
demos/benchmarks/pubspec.yaml
demos/django-todolist/pubspec.yaml
demos/firebase-nodejs-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.yaml
demos/supabase-todolist/pubspec.yaml
demos/supabase-trello/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml
packages/powersync_core/CHANGELOG.md
packages/powersync_core/lib/src/database/native/native_powersync_database.dart
packages/powersync_core/lib/src/database/powersync_db_mixin.dart
packages/powersync_core/lib/src/database/web/web_powersync_database.dart
packages/powersync_core/lib/src/version.dart
packages/powersync_core/pubspec.yaml
packages/powersync_core/test/streaming_sync_test.dart
packages/powersync_core/test/utils/abstract_test_utils.dart
packages/powersync_core/test/utils/web_test_utils.dart
packages/powersync_sqlcipher/CHANGELOG.md
packages/powersync_sqlcipher/pubspec.yaml

In the `connectInternal()` method used to establish a connection to the sync service, we await `initialize()`. That can be a problem when `connect()` is the first call on the database, because writing the schema also acquires the lock used to guard `connectInternal()`.
This fixes the issue by awaiting `initialize()` in `connect()`, before acquiring the sync connect lock and calling `initialize()`. I've also added a test calling `connect()` immediately after opening the database to validate this.
This is the second time I get to fix this [exact regression](https://github.com/powersync-ja/powersync-kotlin/pull/170), yikes 😬 At least in Kotlin we've not seen too many concurrency issues after that though...

Fix deadlock on immediate connect call

---

packages/powersync_core/lib/src/crud.dart
packages/powersync_core/lib/src/schema.dart
packages/powersync_core/test/crud_test.dart
packages/powersync_core/test/schema_test.dart

This exposes the new table options introduced in version 0.3.13 of the core extension, namely:
- `include_old` (either a boolean or an array of column names): Adds an `old` entry to the `ps_crud.data` JSON object that includes old values for updates.
- `include_old_only_when_changed`: Skip unchanged values from updates.
- `include_metadata`: Adds a `_metadata` column that can be written to for updates. It's reported through `CrudEntry.metadata` afterwards.
- `ignore_empty_update`: Don't create `ps_crud` entries for `UPDATE` statements that didn't change any values. 
Most of this feature is tested in the core extension, this adds a few simple tests ensuring we forward options correctly.

Add new schema options

---

demos/benchmarks/pubspec.lock
demos/django-todolist/pubspec.lock
demos/firebase-nodejs-todolist/pubspec.lock
demos/supabase-anonymous-auth/pubspec.lock
demos/supabase-edge-function-auth/pubspec.lock
demos/supabase-simple-chat/pubspec.lock
demos/supabase-todolist-drift/pubspec.lock
demos/supabase-todolist-optional-sync/pubspec.lock
demos/supabase-todolist/pubspec.lock
demos/supabase-trello/pubspec.lock
packages/powersync_core/lib/src/database/web/web_powersync_database.dart
packages/powersync_core/lib/src/web/sync_worker.dart
packages/powersync_core/pubspec.yaml

For a long time, `package:http` was implemented using `XMLHttpRequest` on the web. Since version 1.3.0 however, it has finally been migrated to `fetch`. Unfortunately, it called `window.fetch` which makes that version unavailable in workers. That has been fixed in version 1.4.0, which means that we can use an upstream `BrowserClient` instead of depending on `fetch_client`.

Replace `fetch_client` package with regular http

---

packages/powersync_core/lib/src/abort_controller.dart
packages/powersync_core/lib/src/database/native/native_powersync_database.dart
packages/powersync_core/lib/src/database/powersync_database_impl_stub.dart
packages/powersync_core/lib/src/database/powersync_db_mixin.dart
packages/powersync_core/lib/src/database/web/web_powersync_database.dart
packages/powersync_core/test/streaming_sync_test.dart
packages/powersync_core/test/test_server.dart
packages/powersync_core/test/utils/abstract_test_utils.dart

To prevent duplicate concurrent sync connections, we guard `connect()` and `disconnect()` calls in mutexes. And since the mutex implementation is not reentrant, there's a check ensuring another call to `.lock()` throws if it comes from an async zone that already holds the mutex.
By design, async zones are quite sticky: Every callback we register in that zone will also run in the same zone. So when we call `connectInternal` on the native database, all message handlers from the isolate are handled in the zone originally establishing the connection.
This means that these callbacks can't call `disconnect()`, which is unfortunate because the lock is not actually held at that point. This fixes that issue by passing the zone originally calling `connect()` which is then used to run callbacks. …

Allow disconnecting in `fetchCredentials` callback

---

packages/powersync_core/lib/src/sync/sync_status.dart
packages/powersync_core/test/in_memory_sync_test.dart

In some cases, it was possible for reported download progress to go out of the normal range of 0..1, e.g.:
1. Start with empty db, create 100k rows, let client sync and stop at around 50k.
2. Disconnect client, delete 90k rows, re-deploy sync rules.
3. Reconnect client.
4. Observe that it claims to have downloaded 50k rows out of 10k total.
This is because the sync progress heuristic assumes that buckets won't shrink in size. In this PR, we try to detect a bucket being reduced so much that we'd be over 100% when the sync has just started. In this case, we throw local progress away and start from 0. There are still some issues associated with progress around defrags (e.g. since checksums changed, we're downloading everything twice and will have progress go from 0 to 1 twice), but this …

Fix reported progress around compaction / defrag

---

CHANGELOG.md
demos/benchmarks/pubspec.yaml
demos/django-todolist/pubspec.yaml
demos/firebase-nodejs-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.yaml
demos/supabase-todolist/pubspec.yaml
demos/supabase-trello/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml
packages/powersync_core/CHANGELOG.md
packages/powersync_core/lib/src/version.dart
packages/powersync_core/pubspec.yaml
packages/powersync_core/test/watch_test.dart
packages/powersync_sqlcipher/CHANGELOG.md
packages/powersync_sqlcipher/example/pubspec.yaml
packages/powersync_sqlcipher/pubspec.yaml

This prepares a release with these changes since the last one:
- Replace fetch client with regular `package:http`: https://github.com/powersync-ja/powersync.dart/pull/276
- Allow disconnecting in credentials callback: https://github.com/powersync-ja/powersync.dart/pull/279
- Refactor sync client and options: https://github.com/powersync-ja/powersync.dart/pull/281
- Allow subclassing SQLCipher factory: https://github.com/powersync-ja/powersync.dart/pull/284
- Fix progress around compactions and defragmentations: https://github.com/powersync-ja/powersync.dart/pull/287

Prepare release

---

demos/benchmarks/ios/Podfile.lock
demos/benchmarks/macos/Podfile.lock
demos/django-todolist/ios/Podfile.lock
demos/django-todolist/macos/Podfile.lock
demos/firebase-nodejs-todolist/ios/Podfile.lock
demos/supabase-anonymous-auth/ios/Podfile.lock
demos/supabase-anonymous-auth/macos/Podfile.lock
demos/supabase-edge-function-auth/ios/Podfile.lock
demos/supabase-edge-function-auth/macos/Podfile.lock
demos/supabase-simple-chat/ios/Podfile.lock
demos/supabase-simple-chat/macos/Podfile.lock
demos/supabase-todolist-drift/ios/Podfile.lock
demos/supabase-todolist-drift/macos/Podfile.lock
demos/supabase-todolist-optional-sync/ios/Podfile.lock
demos/supabase-todolist-optional-sync/macos/Podfile.lock
demos/supabase-todolist/ios/Podfile.lock
demos/supabase-todolist/macos/Podfile.lock
demos/supabase-trello/ios/Podfile.lock
demos/supabase-trello/macos/Podfile.lock
packages/powersync_flutter_libs/android/build.gradle
packages/powersync_flutter_libs/ios/powersync_flutter_libs.podspec
packages/powersync_flutter_libs/macos/powersync_flutter_libs.podspec
packages/powersync_sqlcipher/example/ios/Podfile.lock
packages/powersync_sqlcipher/example/ios/Runner.xcodeproj/project.pbxproj
packages/powersync_sqlcipher/example/ios/Runner.xcworkspace/contents.xcworkspacedata
packages/powersync_sqlcipher/example/pubspec.lock
packages/sqlite3_wasm_build/build.sh
scripts/download_core_binary_demos.dart
scripts/init_powersync_core_binary.dart

This updates the core extension (used for tests, to build the WASM bundle and for `powersync_flutter_libs`) to version `0.4.0`.

Update powersync-sqlite-core to 0.4.0

---

packages/powersync_core/lib/src/database/core_version.dart
packages/powersync_core/lib/src/database/native/native_powersync_database.dart
packages/powersync_core/lib/src/database/powersync_database_impl_stub.dart
packages/powersync_core/lib/src/database/powersync_db_mixin.dart
packages/powersync_core/lib/src/database/web/web_powersync_database.dart
packages/powersync_core/lib/src/sync/bucket_storage.dart
packages/powersync_core/lib/src/sync/instruction.dart
packages/powersync_core/lib/src/sync/mutable_sync_status.dart
packages/powersync_core/lib/src/sync/options.dart
packages/powersync_core/lib/src/sync/streaming_sync.dart
packages/powersync_core/lib/src/sync/sync_status.dart
packages/powersync_core/lib/src/web/sync_worker.dart
packages/powersync_core/lib/src/web/sync_worker_protocol.dart
packages/powersync_core/lib/src/web/web_bucket_storage.dart
packages/powersync_core/test/bucket_storage_test.dart
packages/powersync_core/test/in_memory_sync_test.dart

This adds the `SyncOptions.syncImplementation` field to control which implementation is used for parsing and applying lines received from the sync service: Two options are available: `SyncClientImplementation.dart` (the existing implementation) and a new `SyncClientImplementation.rust`. For now, `dart` is still the default implementation. To allow us to eventually remove the Dart-based implementation without a breaking change, `SyncClientImplementation.dart` is already marked as deprecated (users should use `SyncClientImplementation.defaultClient` instead, which we can eventually point to `SyncClientImplementation.rust`).
The new implementation based on the core extension follows the same pattern used in our other SDKs: We send `start` to `powersync_control`, receive an instruction to …

Option to use core exension for sync logic

---

packages/powersync_core/lib/src/exceptions.dart

We should catch Exception, not Error. This resulted in errors like this:
```
FormatException: Unexpected character (at character 1)
<html>
^
```
With this change, we're getting the expected exception:
```
SyncResponseException: 503 Service Unavailable
```

Fix http error parsing

---

packages/powersync_core/lib/src/database/powersync_database.dart
packages/powersync_core/test/utils/abstract_test_utils.dart

`PowerSyncDatabase.withDatabase` was declaring `loggers` instead of `logger`. This changes it while keeping the wrong one as deprecated to avoid breaking.

Fix typo in method parameter: loggers -> logger

---

CHANGELOG.md
demos/benchmarks/pubspec.yaml
demos/django-todolist/pubspec.yaml
demos/firebase-nodejs-todolist/pubspec.yaml
demos/supabase-anonymous-auth/pubspec.yaml
demos/supabase-edge-function-auth/pubspec.yaml
demos/supabase-simple-chat/pubspec.yaml
demos/supabase-todolist-drift/pubspec.yaml
demos/supabase-todolist-optional-sync/pubspec.yaml
demos/supabase-todolist/pubspec.yaml
demos/supabase-trello/pubspec.yaml
packages/powersync/CHANGELOG.md
packages/powersync/pubspec.yaml
packages/powersync_attachments_helper/CHANGELOG.md
packages/powersync_attachments_helper/pubspec.yaml
packages/powersync_core/CHANGELOG.md
packages/powersync_core/lib/src/version.dart
packages/powersync_core/pubspec.yaml
packages/powersync_flutter_libs/CHANGELOG.md
packages/powersync_flutter_libs/pubspec.yaml
packages/powersync_sqlcipher/CHANGELOG.md
packages/powersync_sqlcipher/example/pubspec.yaml
packages/powersync_sqlcipher/pubspec.yaml

This prepares a release for the following packages:
- powersync_core@1.5.0
- powersync@1.15.0
- powersync_sqlcipher@0.1.10
- powersync_attachments_helper@0.6.18+11
- powersync_flutter_libs@0.4.10
The only changes are updating the core extension version and introducing experimental support for raw tables.

Prepare minor release

---

packages/powersync_core/lib/src/sync/stream_utils.dart
packages/powersync_core/lib/src/sync/streaming_sync.dart
packages/powersync_core/pubspec.yaml
packages/powersync_core/test/in_memory_sync_test.dart
packages/powersync_core/test/server/sync_server/in_memory_sync_server.dart

This relies on https://github.com/powersync-ja/powersync-service/pull/310 and requests sync lines in a binary format when the Rust client is used.
We still support the sync service responding with text lines, but the response handling now supports splitting the BSON stream and sends that as a preference to ensure we can handle binary data. This makes the Dart SDK ready for binary data without relying on RSocket, which is poorly supported on Dart.
I've tested this with the sync service from the linked PR, and I've also expanded all sync unit tests to include the binary stream. I've also tested this PR with an old sync service, and `main` with the new sync service to make sure content negotiation works like it's supposed to.

Rust client: Request sync lines as BSON

---

packages/powersync_core/lib/src/database/powersync_db_mixin.dart
packages/powersync_core/test/crud_test.dart

This adds `nextCrudTransactions()`, returning a stream of transactions starting with the oldest one.
By returning a stream, developers can batch multiple transactions in a flexible way, cancelling their stream subscription (usually by breaking out of an `await for` loop) once the batch has an appropriate size. By still returning transactions, we ensure no partial transactions are uploaded (a typical problem with `getNextCrudBatch()`).

Add nextCrudTransactions() stream

---

demos/supabase-todolist/lib/attachments/queue.dart
packages/powersync_core/doc/attachments.md

This deletes the unused `deletePhotoAttachment` method and expands attachments docs to link to references in the app using the new APIs.

Attachments docs: Point to uses in example
